kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: 123
nodes:
- role: control-plane
  image: kindest/node:v1.23.17@sha256:59c989ff8a517a93127d4a536e7014d28e235fb3529d9fba91b3951d461edfdb
- role: worker
  image: kindest/node:v1.23.17@sha256:59c989ff8a517a93127d4a536e7014d28e235fb3529d9fba91b3951d461edfdb
- role: worker
  image: kindest/node:v1.23.17@sha256:59c989ff8a517a93127d4a536e7014d28e235fb3529d9fba91b3951d461edfdb
- role: worker
  image: kindest/node:v1.23.17@sha256:59c989ff8a517a93127d4a536e7014d28e235fb3529d9fba91b3951d461edfdb
networking:
  # apiServerAddress: 192.168.56.3
  # apiServerPort: 6443
  podSubnet: 10.243.0.0/16
  serviceSubnet: 10.123.0.0/16
  # disableDefaultCNI: true